// skills/tailwind-ui/assets/code/v3/vue/application-ui/avatars/avatar-group-stacked-top-to-bottom.vue
<template>
  <div class="isolate flex -space-x-1 overflow-hidden">
    <img class="relative z-30 inline-block size-6 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900" src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
    <img class="relative z-20 inline-block size-6 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900" src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
    <img class="relative z-10 inline-block size-6 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900" src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80" alt="" />
    <img class="relative z-0 inline-block size-6 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
  </div>

  <div class="isolate flex -space-x-2 overflow-hidden">
    <img class="relative z-30 inline-block size-8 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900" src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
    <img class="relative z-20 inline-block size-8 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900" src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
    <img class="relative z-10 inline-block size-8 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900" src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80" alt="" />
    <img class="relative z-0 inline-block size-8 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
  </div>

  <div class="isolate flex -space-x-2 overflow-hidden">
    <img class="relative z-30 inline-block size-10 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900" src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
    <img class="relative z-20 inline-block size-10 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900" src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
    <img class="relative z-10 inline-block size-10 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900" src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80" alt="" />
    <img class="relative z-0 inline-block size-10 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="" />
  </div>
</template>

// skills/tailwind-ui/assets/code/v3/react/application-ui/avatars/avatar-group-stacked-top-to-bottom.tsx
export default function Example() {
  return (
    <>
      <div className="isolate flex -space-x-1 overflow-hidden">
        <img
          alt=""
          src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
          className="relative z-30 inline-block size-6 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900"
        />
        <img
          alt=""
          src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
          className="relative z-20 inline-block size-6 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900"
        />
        <img
          alt=""
          src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80"
          className="relative z-10 inline-block size-6 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900"
        />
        <img
          alt=""
          src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
          className="relative z-0 inline-block size-6 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900"
        />
      </div>

      <div className="isolate flex -space-x-2 overflow-hidden">
        <img
          alt=""
          src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
          className="relative z-30 inline-block size-8 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900"
        />
        <img
          alt=""
          src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
          className="relative z-20 inline-block size-8 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900"
        />
        <img
          alt=""
          src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80"
          className="relative z-10 inline-block size-8 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900"
        />
        <img
          alt=""
          src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
          className="relative z-0 inline-block size-8 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900"
        />
      </div>

      <div className="isolate flex -space-x-2 overflow-hidden">
        <img
          alt=""
          src="https://images.unsplash.com/photo-1491528323818-fdd1faba62cc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
          className="relative z-30 inline-block size-10 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900"
        />
        <img
          alt=""
          src="https://images.unsplash.com/photo-1550525811-e5869dd03032?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
          className="relative z-20 inline-block size-10 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900"
        />
        <img
          alt=""
          src="https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.25&w=256&h=256&q=80"
          className="relative z-10 inline-block size-10 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900"
        />
        <img
          alt=""
          src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
          className="relative z-0 inline-block size-10 rounded-full outline outline-1 -outline-offset-1 outline-black/5 ring-2 ring-white dark:outline-white/10 dark:ring-gray-900"
        />
      </div>
    </>
  )
}
