// skills/tailwind-ui/assets/code/v3/vue/application-ui/list-containers/card-with-dividers.vue
<template>
  <div class="overflow-hidden rounded-md bg-white shadow dark:bg-gray-800/50 dark:shadow-none dark:outline dark:outline-1 dark:-outline-offset-0 dark:outline-white/10">
    <ul role="list" class="divide-y divide-gray-200 dark:divide-white/10">
      <li v-for="item in items" :key="item.id" class="px-6 py-4">
        <!-- Your content -->
      </li>
    </ul>
  </div>
</template>

<script setup>
const items = [{ id: 1 }, { id: 2 }, { id: 3 }]
</script>

// skills/tailwind-ui/assets/code/v3/react/application-ui/list-containers/card-with-dividers.tsx
const items = [{ id: 1 }, { id: 2 }, { id: 3 }]

export default function Example() {
  return (
    <div className="overflow-hidden rounded-md bg-white shadow dark:bg-gray-800/50 dark:shadow-none dark:outline dark:outline-1 dark:-outline-offset-0 dark:outline-white/10">
      <ul role="list" className="divide-y divide-gray-200 dark:divide-white/10">
        {items.map((item) => (
          <li key={item.id} className="px-6 py-4">
            {/* Your content */}
          </li>
        ))}
      </ul>
    </div>
  )
}
