// skills/tailwind-ui/assets/code/v3/vue/application-ui/dividers/with-toolbar.vue
<template>
  <div class="flex items-center">
    <div class="w-full border-t border-gray-300 dark:border-white/15" aria-hidden="true"></div>
    <div class="relative flex justify-center">
      <span class="isolate inline-flex -space-x-px rounded-md shadow-sm dark:shadow-none">
        <button type="button" class="relative inline-flex items-center rounded-l-md bg-white px-3 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-10 dark:bg-white/5 dark:ring-gray-700 dark:hover:bg-white/10">
          <span class="sr-only">Edit</span>
          <PencilIcon class="size-5" aria-hidden="true" />
        </button>
        <button type="button" class="relative inline-flex items-center bg-white px-3 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-10 dark:bg-white/5 dark:ring-gray-700 dark:hover:bg-white/10">
          <span class="sr-only">Attachment</span>
          <PaperClipIcon class="size-5" aria-hidden="true" />
        </button>
        <button type="button" class="relative inline-flex items-center bg-white px-3 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-10 dark:bg-white/5 dark:ring-gray-700 dark:hover:bg-white/10">
          <span class="sr-only">Annotate</span>
          <ChatBubbleBottomCenterTextIcon class="size-5" aria-hidden="true" />
        </button>
        <button type="button" class="relative inline-flex items-center rounded-r-md bg-white px-3 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-10 dark:bg-white/5 dark:ring-gray-700 dark:hover:bg-white/10">
          <span class="sr-only">Delete</span>
          <TrashIcon class="size-5" aria-hidden="true" />
        </button>
      </span>
    </div>
    <div class="w-full border-t border-gray-300 dark:border-white/15" aria-hidden="true"></div>
  </div>
</template>

<script setup>
import { ChatBubbleBottomCenterTextIcon, PaperClipIcon, PencilIcon, TrashIcon } from '@heroicons/vue/20/solid'
</script>

// skills/tailwind-ui/assets/code/v3/react/application-ui/dividers/with-toolbar.tsx
import { ChatBubbleBottomCenterTextIcon, PaperClipIcon, PencilIcon, TrashIcon } from '@heroicons/react/20/solid'

export default function Example() {
  return (
    <div className="flex items-center">
      <div aria-hidden="true" className="w-full border-t border-gray-300 dark:border-white/15" />
      <div className="relative flex justify-center">
        <span className="isolate inline-flex -space-x-px rounded-md shadow-sm dark:shadow-none">
          <button
            type="button"
            className="relative inline-flex items-center rounded-l-md bg-white px-3 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-10 dark:bg-white/5 dark:ring-gray-700 dark:hover:bg-white/10"
          >
            <span className="sr-only">Edit</span>
            <PencilIcon aria-hidden="true" className="size-5" />
          </button>
          <button
            type="button"
            className="relative inline-flex items-center bg-white px-3 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-10 dark:bg-white/5 dark:ring-gray-700 dark:hover:bg-white/10"
          >
            <span className="sr-only">Attachment</span>
            <PaperClipIcon aria-hidden="true" className="size-5" />
          </button>
          <button
            type="button"
            className="relative inline-flex items-center bg-white px-3 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-10 dark:bg-white/5 dark:ring-gray-700 dark:hover:bg-white/10"
          >
            <span className="sr-only">Annotate</span>
            <ChatBubbleBottomCenterTextIcon aria-hidden="true" className="size-5" />
          </button>
          <button
            type="button"
            className="relative inline-flex items-center rounded-r-md bg-white px-3 py-2 text-gray-400 ring-1 ring-inset ring-gray-300 hover:bg-gray-50 focus:z-10 dark:bg-white/5 dark:ring-gray-700 dark:hover:bg-white/10"
          >
            <span className="sr-only">Delete</span>
            <TrashIcon aria-hidden="true" className="size-5" />
          </button>
        </span>
      </div>
      <div aria-hidden="true" className="w-full border-t border-gray-300 dark:border-white/15" />
    </div>
  )
}
