// skills/tailwind-ui/assets/code/v3/vue/application-ui/cards/card-edge-to-edge-on-mobile.vue
<template>
  <!-- Be sure to use this with a layout container that is full-width on mobile -->
  <div class="overflow-hidden bg-white shadow sm:rounded-lg dark:bg-gray-800/50 dark:shadow-none dark:outline dark:outline-1 dark:-outline-offset-1 dark:outline-white/10">
    <div class="px-4 py-5 sm:p-6">
      <!-- Content goes here -->
    </div>
  </div>
</template>

// skills/tailwind-ui/assets/code/v3/react/application-ui/cards/card-edge-to-edge-on-mobile.tsx
export default function Example() {
  return (
    <>
      {/* Be sure to use this with a layout container that is full-width on mobile */}
      <div className="overflow-hidden bg-white shadow sm:rounded-lg dark:bg-gray-800/50 dark:shadow-none dark:outline dark:outline-1 dark:-outline-offset-1 dark:outline-white/10">
        <div className="px-4 py-5 sm:p-6">{/* Content goes here */}</div>
      </div>
    </>
  )
}
