// skills/tailwind-ui/assets/code/v3/vue/application-ui/input-groups/input-with-label-and-help-text.vue
<template>
  <div>
    <label for="email" class="block text-sm/6 font-medium text-gray-900 dark:text-white">Email</label>
    <div class="mt-2">
      <input type="email" name="email" id="email" class="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-white/10 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500" placeholder="you@example.com" aria-describedby="email-description" />
    </div>
    <p class="mt-2 text-sm text-gray-500 dark:text-gray-400" id="email-description">We'll only use this for spam.</p>
  </div>
</template>

// skills/tailwind-ui/assets/code/v3/react/application-ui/input-groups/input-with-label-and-help-text.tsx
export default function Example() {
  return (
    <div>
      <label htmlFor="email" className="block text-sm/6 font-medium text-gray-900 dark:text-white">
        Email
      </label>
      <div className="mt-2">
        <input
          id="email"
          name="email"
          type="email"
          placeholder="you@example.com"
          aria-describedby="email-description"
          className="block w-full rounded-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-white/10 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500"
        />
      </div>
      <p id="email-description" className="mt-2 text-sm text-gray-500 dark:text-gray-400">
        We'll only use this for spam.
      </p>
    </div>
  )
}
