// skills/tailwind-ui/assets/code/v3/vue/application-ui/input-groups/inputs-with-shared-borders.vue
<template>
  <div>
    <fieldset>
      <legend class="block text-sm/6 font-medium text-gray-900 dark:text-white">Card details</legend>
      <div class="mt-2 grid grid-cols-2">
        <div class="col-span-2">
          <input type="text" id="card-number" name="card-number" aria-label="Card number" class="block w-full rounded-t-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:relative focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-gray-700 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500" placeholder="Card number" />
        </div>
        <div class="-mr-px -mt-px">
          <input type="text" id="card-expiration-date" name="card-expiration-date" aria-label="Expiration date" class="block w-full rounded-bl-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:relative focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-gray-700 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500" placeholder="MM / YY" />
        </div>
        <div class="-mt-px">
          <input type="text" id="card-cvc" name="card-cvc" aria-label="CVC" class="block w-full rounded-br-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:relative focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-gray-700 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500" placeholder="CVC" />
        </div>
      </div>
    </fieldset>
    <fieldset class="mt-6">
      <legend class="block text-sm/6 font-medium text-gray-900 dark:text-white">Billing address</legend>
      <div class="mt-2">
        <div class="grid grid-cols-1 focus-within:relative">
          <select id="country" name="country" autocomplete="country-name" aria-label="Country" class="col-start-1 row-start-1 w-full appearance-none rounded-t-md bg-white py-1.5 pl-3 pr-8 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-gray-700 dark:*:bg-gray-800 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500">
            <option>United States</option>
            <option>Canada</option>
            <option>Mexico</option>
          </select>
          <ChevronDownIcon class="pointer-events-none col-start-1 row-start-1 mr-2 size-5 self-center justify-self-end text-gray-500 sm:size-4 dark:text-gray-400" aria-hidden="true" />
        </div>
        <div class="-mt-px">
          <input type="text" id="postal-code" name="postal-code" autocomplete="postal-code" aria-label="ZIP / Postal code" class="block w-full rounded-b-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:relative focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-gray-700 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500" placeholder="ZIP / Postal code" />
        </div>
      </div>
    </fieldset>
  </div>
</template>

<script setup>
import { ChevronDownIcon } from '@heroicons/vue/16/solid'
</script>

// skills/tailwind-ui/assets/code/v3/react/application-ui/input-groups/inputs-with-shared-borders.tsx
import { ChevronDownIcon } from '@heroicons/react/16/solid'

export default function Example() {
  return (
    <div>
      <fieldset>
        <legend className="block text-sm/6 font-medium text-gray-900 dark:text-white">Card details</legend>
        <div className="mt-2 grid grid-cols-2">
          <div className="col-span-2">
            <input
              id="card-number"
              name="card-number"
              type="text"
              placeholder="Card number"
              aria-label="Card number"
              className="block w-full rounded-t-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:relative focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-gray-700 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500"
            />
          </div>
          <div className="-mr-px -mt-px">
            <input
              id="card-expiration-date"
              name="card-expiration-date"
              type="text"
              placeholder="MM / YY"
              aria-label="Expiration date"
              className="block w-full rounded-bl-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:relative focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-gray-700 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500"
            />
          </div>
          <div className="-mt-px">
            <input
              id="card-cvc"
              name="card-cvc"
              type="text"
              placeholder="CVC"
              aria-label="CVC"
              className="block w-full rounded-br-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:relative focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-gray-700 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500"
            />
          </div>
        </div>
      </fieldset>
      <fieldset className="mt-6">
        <legend className="block text-sm/6 font-medium text-gray-900 dark:text-white">Billing address</legend>
        <div className="mt-2">
          <div className="grid grid-cols-1 focus-within:relative">
            <select
              id="country"
              name="country"
              autoComplete="country-name"
              aria-label="Country"
              className="col-start-1 row-start-1 w-full appearance-none rounded-t-md bg-white py-1.5 pl-3 pr-8 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-gray-700 dark:*:bg-gray-800 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500"
            >
              <option>United States</option>
              <option>Canada</option>
              <option>Mexico</option>
            </select>
            <ChevronDownIcon
              aria-hidden="true"
              className="pointer-events-none col-start-1 row-start-1 mr-2 size-5 self-center justify-self-end text-gray-500 sm:size-4 dark:text-gray-400"
            />
          </div>
          <div className="-mt-px">
            <input
              id="postal-code"
              name="postal-code"
              type="text"
              placeholder="ZIP / Postal code"
              autoComplete="postal-code"
              aria-label="ZIP / Postal code"
              className="block w-full rounded-b-md bg-white px-3 py-1.5 text-base text-gray-900 outline outline-1 -outline-offset-1 outline-gray-300 placeholder:text-gray-400 focus:relative focus:outline focus:outline-2 focus:-outline-offset-2 focus:outline-indigo-600 sm:text-sm/6 dark:bg-white/5 dark:text-white dark:outline-gray-700 dark:placeholder:text-gray-500 dark:focus:outline-indigo-500"
            />
          </div>
        </div>
      </fieldset>
    </div>
  )
}
