// skills/tailwind-ui/assets/code/v3/vue/application-ui/section-headings/with-label.vue
<template>
  <div class="border-b border-gray-200 pb-5 dark:border-white/10">
    <div class="-ml-2 -mt-2 flex flex-wrap items-baseline">
      <h3 class="ml-2 mt-2 text-base font-semibold text-gray-900 dark:text-white">Job Postings</h3>
      <p class="ml-2 mt-1 truncate text-sm text-gray-500 dark:text-gray-400">in Engineering</p>
    </div>
  </div>
</template>

// skills/tailwind-ui/assets/code/v3/react/application-ui/section-headings/with-label.tsx
export default function Example() {
  return (
    <div className="border-b border-gray-200 pb-5 dark:border-white/10">
      <div className="-ml-2 -mt-2 flex flex-wrap items-baseline">
        <h3 className="ml-2 mt-2 text-base font-semibold text-gray-900 dark:text-white">Job Postings</h3>
        <p className="ml-2 mt-1 truncate text-sm text-gray-500 dark:text-gray-400">in Engineering</p>
      </div>
    </div>
  )
}
